### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wido-user** [garrettbts/docker-wdio#1]
Hey,
# I'm trying to get this working in my local, i followed the steps provided but end up in the below error.  Could you kindly help me please.  

Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
# For a complete list of commands, visit http://webdriver.io/docs.html.

(node:12) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[06:30:37]  COMMAND POST     "/wd/hub/session"
[06:30:37]  DATA    {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.0.7","name":"webdriverio"}}}
ERROR: Couldn't connect to selenium server
chrome
    at new RuntimeError (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/usr/local/lib/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Thanks in advance,
Raj

**Comment by garrettbates** [comment]
@wido-user Can you confirm you installed docker-toolbox: https://www.docker.com/products/docker-toolbox, then ran `eval $(docker-machine env)`, and then ran ./run.sh?
